gfcli:
  build:
    name:     "CVE-2022-22965"
    arch:     "amd64"
    system:   "linux,darwin,windows"
    mod:      "none"
    pack:     ""
    version:  "v1.0.0"
    output:   "./bin"
    extra:    ""